---
# tasks file for elasticsearch
- name: Include Debian tasks
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install
  ansible.builtin.apt:
    name: elasticsearch
    state: present

- name: Config elasticsearch.yml
  ansible.builtin.copy:
    src: ../templates/elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: "0660"
  notify: restart elasticsearch

- name: Start Elasticsearch.
  service:
    name: elasticsearch
    state: started
    enabled: true

- name: Run Elasticsearch Reset Password Command
  command: /usr/share/elasticsearch/bin/elasticsearch-reset-password auto -u elastic
  args:
    stdin: "y\n"
  register: reset_password_output
