apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./flux-system
- ./operations
- crossplane.yaml
# - clusters-config.yaml
# - crossplane-eks-composition.yaml

# - karpenter-config.yaml
# - karpenter-iam.yaml
# - karpenter.yaml
