{
 "title": "Resource",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total of CPU core in all hosts",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{}) by (cpu))"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage in each state ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\"}[1m])) by (mode)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total of CPU core in host ($instance)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 17, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Load average in 5 minutes ($instance)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 17, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_load5{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU usage in percentage ($instance)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=\"$instance\", mode!=\"idle\"}[1m])) / count(count(node_cpu_seconds_total{instance=\"$instance\"})by (cpu))",
       "legendFormat": "CPU used"
      }
     ]
    },
    {
     "title": "Load average in 15 minutes ($instance)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 17, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_load15{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}