{
 "title": "Resource",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(k8s_deployment_available{k8s_namespace_name =~\"$namespace\"}, k8s_deployment_name)\n"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(k8s_namespace_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(k8s_pod_phase{k8s_namespace_name=\"$namespace\"}, k8s_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Container Filesystem usage($namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_filesystem_usage_bytes{k8s_namespace_name=\"$namespace\"}",
     "legendFormat": "Used by {{k8s_pod_name}} - {{k8s_container_name}}"
    }
   ]
  },
  {
   "title": "Memory usage vs. Memory limit in percentage ($namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( sum(container_memory_working_set_bytes{k8s_namespace_name=\"$namespace\"}) by (k8s_pod_name)\n/ on(k8s_container_name, k8s_pod_name)\nsum(k8s_container_memory_limit_bytes{k8s_namespace_name=\"$namespace\"}) by (k8s_pod_name)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage vs. Request & Limit in cores($pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Used by {{k8s_pod_name}} - {{k8s_container_name}}"
    },
    {
     "expr": "k8s_container_memory_limit_bytes{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Limit  by {{k8s_pod_name}} - {{k8s_container_name}}"
    },
    {
     "expr": "k8s_container_memory_request_bytes{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Request  by {{k8s_pod_name}} - {{k8s_container_name}}"
    }
   ]
  },
  {
   "title": "CPU usage vs. Request/Limit in cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(container_cpu_time_seconds_total{k8s_pod_name=\"$pod\"}[1m])",
     "legendFormat": "Used by - {{k8s_container_name}}"
    },
    {
     "expr": "k8s_container_cpu_limit{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Limit - {{k8s_container_name}}"
    },
    {
     "expr": "k8s_container_cpu_request{k8s_pod_name=\"$pod\"}",
     "legendFormat": "Request - {{k8s_container_name}}"
    }
   ]
  },
  {
   "title": "Pod Usage vs. Limit in Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_time_seconds_total{k8s_namespace_name=\"$namespace\"}[1m])) by (k8s_pod_name)\n/ on(k8s_container_name, k8s_pod_name)\nsum(k8s_container_cpu_limit{k8s_namespace_name=\"$namespace\"}) by (k8s_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true
  }
 ]
}